title: MARCC Scientific Computing Guide
email: marcc-help@marcc.jhu.edu
# description: >-
baseurl: "" # the subpath of your site, e.g. /blog
url: "bradleyrp.github.io/demo" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  marcc-hpc
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
collections:
  notebooks:
    output: true
  articles:
    output: true
